### ISSUE TITLE
Tesztelés - egységtesztek készítése

### ISSUE THREAD

**Issue by hegyiadam** [BME-MIT-IET/Mzperx-iet-2018#10]
## Feladat leírása
Az egyik választott feladatunk a tesztelés részben az egységtesztek készítése.

## A feladat megközelítése
Alapmegközelítésnek a kód alapú tesztkészítést tűztük ki célul. A projekt a kiindulási állapotában nem tartalmaz teszteket.

## Megbízottak
_Lócsi Barbara (@barbaralocsi)
Hegyi Ádám (@hegyiadam)_
Az általunk elvégzett munka ellenőrzésével _Csendes Dávid (@drsylent)_ van megbízva.

## Megoldás menete
A megoldáshoz az xUnit keretrendszert fogjuk hassználni.

**Comment by barbaralocsi** [comment]
[Add test for:](https://github.com/BME-MIT-IET/Mzperx-iet-2018/commit/f5340b03ec45f11db5ccb0a9d3c1ce2349c136bd)
- RDFCollection
- RDFContainer
- RDFMemoryStore
- RDFSelectQuery

**Comment by hegyiadam** [comment]
# Egységtesztek elkészültek
A feladat elvégzése során figyelembe vettük az előírtakat és törekedtünk arra hogy ne egyszerű függvények (getter, setter) függvények működését teszteljük. Mivel azonban a könyvtár jól strukturált így a feladatának megfelelően olyan osztályok szerepelnek benne, amelyek sokkal inkább az adatok tárolására szolgálnak ezért megkerülhetetlen volt viszonylag alapvető (konstruktor, selector jellegű) függvények tesztelése. Mivel a csapat feladatválasztások során, a lefedettség volt a másik szempont és mivel a projekt előzőekben még nem rendelkezett teszt projekttel ezért arra is ügyeltünk, hogy ez a feladat ne a 100%-os lefedettségről szóljon, sokkal inkább a lényeges funkciók feltérképezését szolgálja.

**Comment by barbaralocsi** [comment]
A teszteket sikeresen elkészítettük és részletesen dokumentáltuk a [Tesztelés egységtesztek készítése](https://github.com/BME-MIT-IET/Mzperx-iet-2018/wiki/Tesztel%C3%A9s---egys%C3%A9gtesztek-k%C3%A9sz%C3%ADt%C3%A9se) wiki oldalon.
Az alábi osztályok tesztjeit én készítettem el:
* RDFCollection
* RDFContainer
* RDFMemoryStore
* RDFSelectQuery

A következőket pedig Hegyi Ádám ([hegyiadam](https://github.com/hegyiadam)):
* RDFGraph
* RDFNameSpaceRegister
* RDFResource
* RDFTriple

**Comment by drsylent** [comment]
# Ádám munkájának ellenőrzése
Elégedett vagyok a munkájával, a funkcionalitást rendben tesztelte ott, ahol kiválasztotta. Egy helyen kötöttem bele a munkájába:
[Az egyik tesztosztályában lévő tesztek borasztóan hasonlítottak, érdemben nem javítottak a kód minőségén.](https://github.com/BME-MIT-IET/Mzperx-iet-2018/commit/c8beb8c09d966ededcf44f9e0ab78af31b34aebd)
Megkértem, hogy ezt javítsa ki, és ezt [meg is tette](https://github.com/BME-MIT-IET/Mzperx-iet-2018/blob/61587575167c6f623d58f2c61cb570901dba9d5b/XUnitTestProject1/RDFGraphTest.cs).

**Comment by drsylent** [comment]
# Barbi munkájának ellenőrzése
Barbi is szép teszteket írt, melyek a funkcionalitást rendben fedték, azonban itt is találtam egy kis bökkenőt:
[az egyik tesztje túl komplex volt unit tesztnek](https://github.com/BME-MIT-IET/Mzperx-iet-2018/blob/f5340b03ec45f11db5ccb0a9d3c1ce2349c136bd/XUnitTestProject1/RDFSelectQueryTest.cs).
Ez már annyira mélyen belemegy a rendszer mélyebb részeibe, hogy én inkább rendszertesztnek minősíteném, ezért úgy döntöttünk, hogy ezt a végleges tesztkészletből kivesszük.
