### ISSUE TITLE
Statikus ellenőrzés - manuális kód átvizsgálás

### ISSUE THREAD

**Issue by drsylent** [BME-MIT-IET/Mzperx-iet-2018#5]
Az egyik választott feladatunk a statikus ellenőrzési részben a manuális kód átvizsgálás.
A feladatot így osztottuk fel egymás között:
Hegyi Ádám (@hegyiadam) : a kód helyességét és sebességét figyeli.
Csendes Dávid (@dryslent): a kód olvashatóságát, konvenciók követését, illetve a biztonságot, stabilitást vizsgálja.
Ehhez a Model/RDFGraph.cs útvonalon lévő fájlban lévő RDFGraph osztály metódusainak nagyrészét analizáljuk tüzetesebben.
Az általunk elvégzett munka ellenőrzésével Lócsi Barbara (@barbaralocsi) van megbízva.

**Comment by drsylent** [comment]
# Olvashatósági/konvenció ellenőrzés
### A hozzátartozó pull request: #3 
_A megoldást úgy végeztem el, hogy egy commitban kitöröltem a fájl tartalmát, majd egy újabb commitban visszahelyeztem - ezáltal ezt a commitot tudtam reviewolni (melyet egyébként angolul tettem meg), és ide helyeztem el a saját gondolataimat a kódról._

A kód olvashatóságával összességében nem volt különösebb probléma, átlátható volt, az elnevezések rendben voltak, énmagam meg tudtam érteni hamar, hogy mi miért van ott.
Ellenben a bevett konvenciókat egy részét nem vette figyelembe a programozó, pár alapvető C#-os formai követelmény betartása nem volt sikeres (például kapcsos zárójelek helye), de legalább amit elkezdett így rosszul, azt tartotta végig, ezáltal a kód önmagával legalább konzisztens.

**Comment by drsylent** [comment]
# Biztonsági/stabilitási ellenőrzés
### A hozzátartozó pull request: #4 
_A megoldást úgy végeztem el, hogy egy commitban kitöröltem a fájl tartalmát, majd egy újabb commitban visszahelyeztem - ezáltal ezt a commitot tudtam reviewolni (melyet egyébként angolul tettem meg), és ide helyeztem el a saját gondolataimat a kódról._

Ezt a library-t nem nevezném különösebben biztonságkritikusnak, különösen ezt az osztályát nem, ezért gondoltam, hogy megvizsgálom stabilitás szemszögből is ezt a részét - kivételek dobása előfordulhat-e, nullok kezelése, stb.
Biztonsági szempontból tulajdonképp csak a láthatóságokat vizsgálhattam, amilyen szempontból a kód teljesen rendben volt.
Akárcsak stabilitás terén is, nagyon jól vizsgázott a kód, a programozó nagyon ügyelt arra, hogy null értékek ne kerüljenek be (igyekeztem megnézni a felhasznált osztályokat is, pl. az RDFTriple-t, kaphat-e null értékű azonosítót, mert akkor probléma adódott volna itt több helyen is, de ez már az RDFTriple konstruktorában meg lett gátolva), illetve nagyon kevés kezeletlen kivétel dobódhat - egy úgy vélem többszálú környezetben fordulhatott csak elő (egy iteráció alatt álló lista esetleg módosulhat futás közben), a többi pedig csak szerializációkor jöhet elő, amit pedig inkább a hívónak kell kezelnie véleményem szerint, hisz ő tudja ilyenkor, hogy mi a teendő.

**Comment by hegyiadam** [comment]
# Helyesség ellenőrzése

### A hozzátartozó pull request: #7 

_A megoldást úgy végeztem el, hogy egy commitban kitöröltem a fájl tartalmát, majd egy újabb commitban visszahelyeztem - ezáltal ezt a commitot tudtam reviewolni (melyet egyébként angolul tettem meg), és ide helyeztem el a saját gondolataimat a kódról._

Az library RDFGraph részét ellenőrztem. Ez a rész nem tartalmazott hibát. Sok feleslegesnek tűnő műveletet találtam először végül viszont a kódban azonban a felelősségek szétválasztása és a laza kötés miatt ezek az ellenőrzések szükségszerűek.
Logikailag is minden függvény a rendeltetésének megfelelően működik. A visszatérési értékek és a kivételek kezelése is megfelelő.

**Comment by barbaralocsi** [comment]
Ellenőriztem. A wiki oldalon és a PR-eknél jeleztem megfigyeléseimet.
