### ISSUE TITLE
Statikus ellenőrzés - Statikus analízis eszköz futtatása és jelzett hibák átnézése - VS Code Analyzer

### ISSUE THREAD

**Issue by barbaralocsi** [BME-MIT-IET/Mzperx-iet-2018#8]
Az egyik választott feladatunk a statikus ellenőrzési részben a statikus analízis eszköz futtatása és jelzett hibák átnézése.
A feladatot így osztottuk fel egymás között:
Lócsi Barbara (@barbaralocsi): VS Code Analyzer futtatása és jelzett hibák átnézése.

**Comment by barbaralocsi** [comment]
### A hozzátartozó pull request  [#9](https://github.com/BME-MIT-IET/Mzperx-iet-2018/pull/9)
Javított hibák:
Warning:
#### [CA2202](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca2202-do-not-dispose-objects-multiple-times): Do not dispose objects multiple times
Több helyen is egymásba ágyazott usingok vannak, ez okozta a warningot. Az egymásba ágyaoztt usingok miatt a Dispose többször hívodik. Egy jól implementált Dispose-t lehet többször hívni, de ez nem garantált. A hivatlos dokumentáció szerint a "Suppress Warnings" semmi esetben sem ajánlott, akkor se ha a Dispose helyesen működik, hiszen a Dispose implementálása változhat. A dokumentációban példaként ugyan ez a szituáció fordul elő, így a példában megadott megoldást alkalmaztam a probléma eltüntetéséhez: lecseréltem a külső usingot try-finally blockra.

#### Messages:
IDE0018 Variable declaration can be inlined
IDE0020 Use pattern matching
Ezek kisebb módosítások, melyektől a kód rövidebb, kevesebb ismétlést tartalmaz.

**Comment by hegyiadam** [comment]
A módosításokat ellenőriztem és rendben találtam mindent.
